import Head from 'next/head'
import About from './About'
import React, { useState, useEffect } from 'react'
import Main from './Main'
import Skills from './Skills'
import Projects from './Projects'
import Contact from './Contact'
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs'
import { useTheme } from 'next-themes'

function Home() {
  const { resolvedTheme, setTheme } = useTheme()
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) return null

  return (
    <div className="bg-white dark:bg-gray-900 px-4 sm:px-6 md:px-10 lg:px-40">
      <Head>
        <title>Eshant Manghnani Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <nav className="py-6 mb-12 flex justify-between items-center">
        <h1 className="text-lg sm:text-xl font-burtons text-gray-800 dark:text-white">
          eshantmanghnani
        </h1>

        <div className="flex items-center space-x-4">
          {/* Theme Toggle */}
          <button
            onClick={() => setTheme(resolvedTheme === 'dark' ? 'light' : 'dark')}
            className="p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition"
            aria-label="Toggle Dark Mode"
          >
            {resolvedTheme === 'dark' ? (
              <BsFillSunFill size={20} className="text-white" />
            ) : (
              <BsFillMoonStarsFill size={20} className="text-black" />
            )}
          </button>

          {/* Resume Button */}
          <a
            className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white text-sm sm:text-base px-4 py-2 rounded-md"
            href="https://drive.google.com/file/d/12I4vxYLWVWj9lvuem1ob0Mj9-aHQbbsb/view?usp=sharing"
            target="_blank"
            rel="noopener noreferrer"
          >
            Resume
          </a>
        </div>
      </nav>

      {/* Content Sections */}
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  )
}

export default Home